/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-03-27 14:31:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import BaseDatos.AdministradorBD;

public final class Gestor_005fModelos_005fEditar_005fModelo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\"/>\r\n");
      out.write("\t<title>Phonebook-Gestor Admin</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"view/css/layout.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t<script src=\"view/js/jquery-1.5.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"view/js/hideshow.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"view/js/jquery.tablesorter.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"view/js/jquery.equalHeight.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() \r\n");
      out.write("    \t{ \r\n");
      out.write("      \t  $(\".tablesorter\").tablesorter(); \r\n");
      out.write("   \t } \r\n");
      out.write("\t);\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t//When page loads...\r\n");
      out.write("\t$(\".tab_content\").hide(); //Hide all content\r\n");
      out.write("\t$(\"ul.tabs li:first\").addClass(\"active\").show(); //Activate first tab\r\n");
      out.write("\t$(\".tab_content:first\").show(); //Show first tab content\r\n");
      out.write("\r\n");
      out.write("\t//On Click Event\r\n");
      out.write("\t$(\"ul.tabs li\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"ul.tabs li\").removeClass(\"active\"); //Remove any \"active\" class\r\n");
      out.write("\t\t$(this).addClass(\"active\"); //Add \"active\" class to selected tab\r\n");
      out.write("\t\t$(\".tab_content\").hide(); //Hide all tab content\r\n");
      out.write("\r\n");
      out.write("\t\tvar activeTab = $(this).find(\"a\").attr(\"href\"); //Find the href attribute value to identify the active tab + content\r\n");
      out.write("\t\t$(activeTab).fadeIn(); //Fade in the active ID content\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(function(){\r\n");
      out.write("        $('.column').equalHeight();\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");

        String id = request.getParameter("id");
            AdministradorBD admi = new AdministradorBD();
            ResultSet rs = admi.Modelo_a_editar(id);
            rs.next();
            String nombreModelo = rs.getString("NombreModelo");
            int precioNuevo = rs.getInt("PrecioNuevo");
            String sistemaO = rs.getString("SisOperativo");
            String nombreMarca = rs.getString("NombreMarca");
            int camara = rs.getInt("Camara");
            String resolucion = rs.getString("ResolucionC");
            String memoria = rs.getString("MemoriaInterna");
            rs.close();
         
      out.write("\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<hgroup>\r\n");
      out.write("\t\t\t<h1 class=\"site_title\"><a href=\"index.html\"><img src=\"images/phonebookLogo1.png\" width=\"343\" height=\"80\"></a></h1>\r\n");
      out.write("\t\t\t<h2 class=\"section_title\"><!--texto --></h2><div class=\"btn_view_site\"><a href=\"#\"><img src=\"images/angel.jpg\" width=\"20\" height=\"20\"> Ãngel Sierra</a></div>\r\n");
      out.write("\t\t</hgroup>\r\n");
      out.write("\t</header> <!-- end of header bar -->\r\n");
      out.write("\t\r\n");
      out.write("  <section id=\"secondary_bar\">\r\n");
      out.write("\t\t<div class=\"user\">\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\t<!-- <a class=\"logout_user\" href=\"#\" title=\"Logout\">Logout</a> -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div class=\"breadcrumbs_container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section><!-- end of secondary bar -->\r\n");
      out.write("\t\r\n");
      out.write("\t<aside id=\"sidebar\" class=\"column\">\r\n");
      out.write("\t\t<h2>MenÃº</h2>\r\n");
      out.write("\t\t<hr/>\r\n");
      out.write("\t\t\r\n");
      out.write("        <h3>Gestor_Marcas</h3>\r\n");
      out.write("\t\t<ul class=\"toggle\">\r\n");
      out.write("\t\t\t<li class=\"icn_new_article\"><a href=\"Gestor_Marcas_Crear_Marcas.html\">Crear_Marcas</a></li>\r\n");
      out.write("            <li class=\"icn_categories\"><a href=\"Gestor_Marcas_Lista_Marcas.html\">Lista_Marcas</a></li>\r\n");
      out.write("            \r\n");
      out.write("\t\t</ul>\r\n");
      out.write("        \r\n");
      out.write("\t\t<h3>Gestor_Modelos</h3>\r\n");
      out.write("        \t<ul class=\"toggle\">\r\n");
      out.write("\t\t\t<li class=\"icn_new_article\"><a href=\"Gestor_Modelos_Crear_Modelo.html\">Crear_Modelo</a></li>\r\n");
      out.write("            <li class=\"icn_categories\"><a href=\"Gestor_Modelos_Lista_Modelos.html\">Lista_Modelos</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("        \r\n");
      out.write("        <h3>Gestor_Anuncios</h3>\r\n");
      out.write("        \t<ul class=\"toggle\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("            <li class=\"icn_categories\"><a href=\"Gestor_Anuncios_Lista_Anuncios.html\">Lista_Anuncios</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t</aside><!-- end of sidebar -->\r\n");
      out.write("\t\r\n");
      out.write("\t<section id=\"main\" class=\"column\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h4 class=\"alert_info\">Phonebook | Gestor_Marcas | Editar_Modelo</h4>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<article class=\"module width_full\">\r\n");
      out.write("\t\t\t<header><h3>Editar_Modelo</h3></header>\r\n");
      out.write("\t\t\t<div class=\"tab_container\" style=\"\">\r\n");
      out.write("\t\t\t<div id=\"tab1\" class=\"tab_content\">\r\n");
      out.write("\t\t\t\t<div class=\"module_content\">\r\n");
      out.write("\t\t\t\t<form action=\"Eliminar_Editar_modelo.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("                                                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print(id);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Nombre Modelo</label>\r\n");
      out.write("                                                        <input type=\"text\" name=\"nombreModelo\" value=\"");
      out.print(nombreModelo);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<label>Precio Nuevo</label>\r\n");
      out.write("                                                        <input type=\"text\" name=\"precioNuevo\" value=\"");
      out.print(precioNuevo);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<label>Sistema Operativo</label>\r\n");
      out.write("                                                        <input type=\"text\" name=\"sistemaO\" value=\"");
      out.print(sistemaO);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("                                                <fieldset>\r\n");
      out.write("                                                                                                    ");

                                                            ResultSet rs2 = admi.marcas();

                                                         
      out.write("       \r\n");
      out.write("                                                    <label>Marcas</label>\r\n");
      out.write("                                                            <select id=\"Field9\" name=\"sel_marca\" onchange=\"seleccion_marca(this.value);\">\r\n");
      out.write("                                                                            <option value='0'>Selecciona una marca</option>\r\n");
      out.write("                                                                          ");

                                                                            while (rs2.next()){
                                                                            int idMarca = rs2.getInt("idMarca");
                                                                            String sel_marca = rs2.getString("NombreMarca");
                                                                            if(!sel_marca.equals(nombreMarca)){
                                                                            out.println("<option value='"+idMarca+"'>"+sel_marca+"</option>");
                                                                            }else{
                                                                                out.println("<option value='"+idMarca+"' selected=\"selected\">"+sel_marca+"</option>");
                                                                            }

                                                                                    }
                                                                            rs.close();
                                                                            
      out.write("        \r\n");
      out.write("                                                                            </select>\r\n");
      out.write("                                                </fieldset>    \r\n");
      out.write("                                                            <fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<label>Camara</label>\r\n");
      out.write("                                                        <select name=\"sel_camara\">\r\n");
      out.write("                                                            ");

                                                                if(camara == 1){
                                                                  out.println("<option value='"+camara+"' selected=\"selected\">Si</option>");
                                                                  out.println("<option value='0'>No</option>");
                                                                }else{
                                                                  out.println("<option value='"+camara+"' selected=\"selected\">No</option>");
                                                                   out.println("<option value='1'>Si</option>");
                                                                }
                                                            
      out.write("\r\n");
      out.write("                                                            </select>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<label>Resolución Camara</label>\r\n");
      out.write("                                                        <select name=\"sel_resolucion\">\r\n");
      out.write("                                                            ");
out.println("<option value='"+resolucion+"' selected=\"selected\">"+resolucion+"</option>");
      out.write("\r\n");
      out.write("                                                            <option value=\"0 mpx\">0 mpx</option>\r\n");
      out.write("                                                            <option value=\"2 mpx\">2 mpx</option>\r\n");
      out.write("                                                            <option value=\"5 mpx\">5 mpx</option>\r\n");
      out.write("                                                            <option value=\"8 mpx\">8 mpx</option>\r\n");
      out.write("                                                            <option value=\"12 mpx\">12 mpx</option>\r\n");
      out.write("                                                            <option value=\"20 mpx\">20 mpx</option>\r\n");
      out.write("                                                        </select>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<label>Memoria Interna(GB)</label>\r\n");
      out.write("                                                        <select name=\"sel_memoria\">\r\n");
      out.write("                                                            ");
out.println("<option value='"+memoria+"' selected=\"selected\">"+memoria+"</option>");
      out.write("\r\n");
      out.write("                                                            <option value=\".512 gb\">0.512 gb</option>\r\n");
      out.write("                                                            <option value=\"2 gb\">2 gb</option>\r\n");
      out.write("                                                            <option value=\"4 gb\">4 gb</option>\r\n");
      out.write("                                                            <option value=\"8 gb\">8 gb</option>\r\n");
      out.write("                                                            <option value=\"16 gb\">16 gb</option>\r\n");
      out.write("                                                            <option value=\"32 gb\">32 gb</option>\r\n");
      out.write("                                                            <option value=\"64 gb\">64 gb</option>\r\n");
      out.write("                                                        </select>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<footer>\r\n");
      out.write("\t\t\t\t<div class=\"submit_link\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Editar Modelo\" class=\"alt_btn\">\t<button type=\"button\" class=\"submit\" onclick=\"href();\">Salir</button>\r\n");
      out.write("                                    \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t</article><!-- end of post new article -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<footer>\r\n");
      out.write("\t\t\t<p><strong>Copyright &copy; 2015 Phonebook</strong></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("                                                            <script>\r\n");
      out.write("                                                                function href(){\r\n");
      out.write("                      window.location=\"http://localhost:8080/PhoneBook/Gestor_Modelos_Lista_Modelos.jsp\";\r\n");
      out.write("                  }    \r\n");
      out.write("                                                                </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
