/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-03-26 22:56:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import BaseDatos.AdministradorBD;
import java.util.*;
import org.apache.commons.fileupload.*;
import org.apache.commons.fileupload.servlet.*;
import org.apache.commons.fileupload.disk.*;
import java.io.*;

public final class insertNuevo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	//Ruta donde se guardara el fichero
	File destino=new File("C:\\xampp3\\htdocs\\PhoneBook\\PhoneBook\\web\\images\\Marcas\\");
	// Convertimos el HTTPRequest en un ContextRequest,
	// este paso es necesario en la ultima version,
	// ya que los metodos de las versiones anteriores
	// se han quedado desfasados.
	ServletRequestContext src=new ServletRequestContext(request);
	
	//Si el formulario es enviado con Multipart
	if(ServletFileUpload.isMultipartContent(src)){
	//Necesario para evitar errores de NullPointerException
	DiskFileItemFactory factory = new DiskFileItemFactory((1024*1024),destino);
	//Creamos un FileUpload
	ServletFileUpload upload=new  ServletFileUpload(factory);
	//Procesamos el request para que nos devuelva una lista
	//con los parametros y ficheros.
	List lista = upload.parseRequest(src);
	File file= null;
	//Recorremos la lista.
	Iterator it = lista.iterator();
         String nombreMarca = null; 
	while(it.hasNext()){
                
                 
		//Rescatamos el fileItem
		FileItem item=(FileItem)it.next();
                 
                        if("nombreMarca".equals(item.getFieldName())){
                           nombreMarca = item.getString();
                        }
		//Comprobamos si es un campo de formulario
		if(item.isFormField())
			//Hacemos lo que queramos con el.
			out.println(item.getFieldName()+"<br>");
               
		else
		{
                        //Si no, es un fichero y lo subimos al servidor.
			//Primero creamos un objeto file a partir del nombre del fichero.
			file=new File(item.getName());
			//Lo escribimos en el disco
			// usando la ruta donde se guardara el fichero
			// y cogiendo el nombre del file
			// Nota: Se podria hacer usando el objeto item en vez del file directamente
			// Pero esto puede causar incompatibilidades segun que navegador, ya que 
			// algunos solo pasan el nombre del fichero subido, pero otros
			// como Iexplorer, pasan la ruta absoluta, y esto crea un pequeño problema al escribir
			// el fichero en el servidor.
                        AdministradorBD sqlCode = new AdministradorBD();
                    
                        
                        
			item.write(new File(destino,"img_"+sqlCode.getUltimoId()+".jpg"));
			out.println("Fichero subido");
                        
                       
                        String urlImage = "img_"+sqlCode.getUltimoId()+".jpg";
                        sqlCode.insertMarca(nombreMarca, urlImage);
                        
			
		}
	}
	}
	

  response.sendRedirect("Gestor_Marcas_Lista_Marcas.jsp");

      out.write("\n");
      out.write("\n");
      out.write("%>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
